spring.application.name=backend
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/banking}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=a3eHALUrspx3EAYTteIsovcnEE2GEsjuXgYNJA1jZWm


spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=puspalbiswas11gd11@gmail.com
spring.mail.password=zbau unxq rdni pqcq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_SECRET}
fraud.ml.url= http://fraud-ml:8001/predict
loan.check.url= http://loan-check:8000/predictloan


gemini.api.key=AIzaSyCVoSdRSQnsb6kkXySu5-0NOzO3uatSRwk
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent